#!/usr/bin/env bash

# install nginx and open port

apt-get install -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Hello World!" > /var/www/html/index.html'
service nginx restart
